### ISSUE TITLE
Improving ability to find datasets of interest on Data Portal

### ISSUE THREAD

**Issue by engreitz** [IGVF/catalog-front-end-issues#11]
1.  The initial dataset exploration table is difficult to view because it's compressed on the right side of the screen

Would it be possible to have an option to collapse the toolbars on the left so there's more space to see the table?

![Image](https://github.com/user-attachments/assets/83a6184c-86a2-4f91-ae18-3bb79eba218b)

2. Summary of datasets ...  It's difficult to understand and find datasets of interest.  Two specific changes that would help:

- Can we move the "Summary" column all the way to the left?  None of the first 3 columns (IDs) are particularly helpful for figuring out what the dataset actually is, for an external user. 
- Can we include a free-text "Submitter Summary", in additional to "Summary"?  e.g. for our Variant-FlowFISH dataset, the text Summary "cas mediated mutagenesis (Variant FlowFISH) integrating a guide (sgRNA) library targeting sequence variants in a genomic locus" is sort of useful, but if I were to rewrite it to be more understandable, it would be "Variant-FlowFISH for PPIF promoter in Jurkat cells (no stimulation): Prime editing tiling mutagenesis of the PPIF promoter, with readouts on PPIF expression", or something like this

**Comment by hitz** [comment]
the tool bar on the left collapses, the little arrow thing to the right of the logo

**Comment by hitz** [comment]
Sorry didn't realize this was 2 parter.
2. I will look into being able the change the order of the columns; I think that there is no one true ordering so they are just ID->alphabetical.  If you click the columns button you can hide all the columns you don't want to see.

We are working to improve the dataset summaries.    FileSets (including MeasurmentSets, AnalysisSets etc) all have a "description" property that is free text.   We try not to use this because compliance is highly variable, so we try to make a consistent summary for each thing.
